#!/usr/bin/env bash
# gen-adr-index.sh — generate the complete ADR index block in README.md from
# ADR frontmatter, keeping the README↔disk index in sync (the drift that
# adr-status-lint.sh warns on).
#
# Enumerates every git-tracked ADR-*.md, reads its frontmatter `status:` and
# `boundary:`, and its H1 title, and emits a markdown table between the markers
#   <!-- ADR-INDEX:START (generated by scripts/gen-adr-index.sh) -->
#   <!-- ADR-INDEX:END -->
# in README.md. If the markers are absent, the section is appended once.
# Re-running regenerates in place (idempotent). Slugs are emitted WITH the .md
# suffix so both the strict (.md-anchored) and lenient adr-status-lint variants
# resolve every entry against a real file.
#
# Usage: ./scripts/gen-adr-index.sh [--check]
#   (no args)  rewrite README.md's generated block in place
#   --check    exit 1 if README.md's block is out of date (no write) — CI hook

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

README="README.md"
START="<!-- ADR-INDEX:START (generated by scripts/gen-adr-index.sh) -->"
END="<!-- ADR-INDEX:END -->"

CHECK=false
[[ "${1:-}" == "--check" ]] && CHECK=true

fm_field() { # $1=file $2=field(status|boundary)
  # Strategy 1: YAML frontmatter `field:`.
  local v
  v="$(awk -v f="$2" '
    NR==1 && $0!="---" { exit }
    NR==1 { next }
    $0=="---" { exit }
    $0 ~ "^"f":" { sub("^"f":[[:space:]]*",""); sub(/[[:space:]]+$/,""); gsub(/^["'\'']|["'\'']$/,""); print; exit }
  ' "$1")"
  if [[ -z "$v" ]]; then
    # Strategy 2: pre-template body-bold `**Status:**` / `**Boundary:**`.
    local label
    label="$(printf '%s' "$2" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')"
    v="$(grep -m1 "^\*\*${label}:\*\*" "$1" 2>/dev/null | sed "s/^\*\*${label}:\*\* *//" )"
    # Keep only the first token for a clean cell (values may trail prose).
    v="${v%% *}"; v="${v%%$'\t'*}"
  fi
  printf '%s' "$v"
}

h1_title() { # first "# " heading, minus leading "# "
  # Strip any embedded ADR-YYYY-MM-DD[-slug] token from the title so the Title
  # cell never carries a bare ADR slug that the README-drift linter would read
  # as a (fileless) index reference — the ADR column already links the file.
  grep -m1 '^# ' "$1" 2>/dev/null \
    | sed 's/^# *//' \
    | sed -E 's/ADR-[0-9]{4}-[0-9]{2}-[0-9]{2}(-[a-z0-9-]+)?//g' \
    | sed -E 's/^[[:space:]]*[—:-]+[[:space:]]*//' \
    | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//' \
    | sed 's/|/\\|/g'
}

build_block() {
  printf '%s\n' "$START"
  echo "## Complete ADR index (generated)"
  echo ""
  echo "Every tracked \`ADR-*.md\` in this corpus, generated from frontmatter by"
  echo "\`scripts/gen-adr-index.sh\`. This is the machine-maintained companion to the"
  echo "curated reading-order index above; it exists so the README↔disk index never"
  echo "drifts (\`adr-status-lint.sh\` warns when it does). Regenerate after adding or"
  echo "renaming an ADR."
  echo ""
  echo "| ADR | Status | Boundary | Title |"
  echo "|---|---|---|---|"
  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    st="$(fm_field "$f" status)"; [[ -z "$st" ]] && st="—"
    bd="$(fm_field "$f" boundary)"; [[ -z "$bd" ]] && bd="—"
    ti="$(h1_title "$f")"; [[ -z "$ti" ]] && ti="—"
    printf '| [`%s`](%s) | %s | %s | %s |\n' "$f" "$f" "$st" "$bd" "$ti"
  done < <(git ls-files 'ADR-*.md' | sort)
  printf '%s\n' "$END"
}

NEW_BLOCK="$(build_block)"

if grep -qF "$START" "$README" 2>/dev/null; then
  # Replace existing block (from START line through END line).
  CURRENT="$(awk -v s="$START" -v e="$END" '
    $0==s {inb=1} inb {print} $0==e {inb=0}
  ' "$README")"
  if [[ "$CURRENT" == "$NEW_BLOCK" ]]; then
    echo "gen-adr-index: README block up to date."
    exit 0
  fi
  $CHECK && { echo "gen-adr-index: README block OUT OF DATE (run scripts/gen-adr-index.sh)"; exit 1; }
  block_file="$(mktemp)"; tmp="$(mktemp)"
  printf '%s\n' "$NEW_BLOCK" > "$block_file"
  awk -v bf="$block_file" -v s="$START" -v e="$END" '
    $0==s { while ((getline line < bf) > 0) print line; close(bf); skip=1; next }
    $0==e { skip=0; next }
    !skip { print }
  ' "$README" > "$tmp"
  mv "$tmp" "$README"
  rm -f "$block_file"
  echo "gen-adr-index: README block regenerated in place."
else
  $CHECK && { echo "gen-adr-index: README has no generated block (run scripts/gen-adr-index.sh)"; exit 1; }
  { echo ""; printf '%s\n' "$NEW_BLOCK"; } >> "$README"
  echo "gen-adr-index: appended generated block to README."
fi
